Crates:
  EXAMPLE_CRATE:
    displayName: Example Crate
    glass: BLACK
    borderGlass: BLACK
    profile: 35c4683e-6174-4aff-b238-17b0b6c8938a #random UUID
    texture: ewogICJ0aW1lc3RhbXAiIDogMTU5NjY0MzUzMzM4MSwKICAicHJvZmlsZUlkIiA6ICI5MThhMDI5NTU5ZGQ0Y2U2YjE2ZjdhNWQ1M2VmYjQxMiIsCiAgInByb2ZpbGVOYW1lIiA6ICJCZWV2ZWxvcGVyIiwKICAic2lnbmF0dXJlUmVxdWlyZWQiIDogdHJ1ZSwKICAidGV4dHVyZXMiIDogewogICAgIlNLSU4iIDogewogICAgICAidXJsIiA6ICJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2QyMTQzOTI0YWM5ODFiYmIwNGI5ZGUyODI4MGE4NWI5MjllYjI4MTA2MmI5N2Q0OWI4NGY2MzI4NTE0MjY2N2UiCiAgICB9CiAgfQp9 #texture data
  EXAMPLE_CRATE_2:
    displayName: Example Crate 2
    glass: BLACK
    borderGlass: BLACK
    profile: bea4df75-88bb-4fce-84a1-294c33eef9f3
    texture: ewogICJ0aW1lc3RhbXAiIDogMTU5NjY0MzUzMzM4MSwKICAicHJvZmlsZUlkIiA6ICI5MThhMDI5NTU5ZGQ0Y2U2YjE2ZjdhNWQ1M2VmYjQxMiIsCiAgInByb2ZpbGVOYW1lIiA6ICJCZWV2ZWxvcGVyIiwKICAic2lnbmF0dXJlUmVxdWlyZWQiIDogdHJ1ZSwKICAidGV4dHVyZXMiIDogewogICAgIlNLSU4iIDogewogICAgICAidXJsIiA6ICJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2QyMTQzOTI0YWM5ODFiYmIwNGI5ZGUyODI4MGE4NWI5MjllYjI4MTA2MmI5N2Q0OWI4NGY2MzI4NTE0MjY2N2UiCiAgICB9CiAgfQp9
    profileSeal: 959d17e9-6df0-4483-850f-3259f1af3f31
    textureSeal: ewogICJ0aW1lc3RhbXAiIDogMTU5NzgwNDI0MzEzMywKICAicHJvZmlsZUlkIiA6ICIxNzhmMTJkYWMzNTQ0ZjRhYjExNzkyZDc1MDkzY2JmYyIsCiAgInByb2ZpbGVOYW1lIiA6ICJzaWxlbnRkZXRydWN0aW9uIiwKICAic2lnbmF0dXJlUmVxdWlyZWQiIDogdHJ1ZSwKICAidGV4dHVyZXMiIDogewogICAgIlNLSU4iIDogewogICAgICAidXJsIiA6ICJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzZmYTZjZDU4ZWZlYzZiODFmYWNkNTIzNzk3NDk2NWIwMGQ3N2ZmZjNhZjVjODZjMTkxNDcxNzY3Y2Q5MzhlOWYiCiAgICB9CiAgfQp9
Chests:
  EXAMPLE_CHEST:
    displayName: Example Chest
    glass: BROWN
    profile: 75f66fcb-80fa-4638-bea7-3e884b72b7b7
    texture: ewogICJ0aW1lc3RhbXAiIDogMTU5NjY0MzUzMzM4MSwKICAicHJvZmlsZUlkIiA6ICI5MThhMDI5NTU5ZGQ0Y2U2YjE2ZjdhNWQ1M2VmYjQxMiIsCiAgInByb2ZpbGVOYW1lIiA6ICJCZWV2ZWxvcGVyIiwKICAic2lnbmF0dXJlUmVxdWlyZWQiIDogdHJ1ZSwKICAidGV4dHVyZXMiIDogewogICAgIlNLSU4iIDogewogICAgICAidXJsIiA6ICJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2QyMTQzOTI0YWM5ODFiYmIwNGI5ZGUyODI4MGE4NWI5MjllYjI4MTA2MmI5N2Q0OWI4NGY2MzI4NTE0MjY2N2UiCiAgICB9CiAgfQp9
Gifts:
  EXAMPLE_GIFT:
    displayName: Example Gift
    paperGlass: BLACK
    ribbonGlass: GRAY
    profile: bbe850d3-7f6e-44ae-956b-01b2c74fd26e
    texture: ewogICJ0aW1lc3RhbXAiIDogMTU5NjY0MzUzMzM4MSwKICAicHJvZmlsZUlkIiA6ICI5MThhMDI5NTU5ZGQ0Y2U2YjE2ZjdhNWQ1M2VmYjQxMiIsCiAgInByb2ZpbGVOYW1lIiA6ICJCZWV2ZWxvcGVyIiwKICAic2lnbmF0dXJlUmVxdWlyZWQiIDogdHJ1ZSwKICAidGV4dHVyZXMiIDogewogICAgIlNLSU4iIDogewogICAgICAidXJsIiA6ICJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2QyMTQzOTI0YWM5ODFiYmIwNGI5ZGUyODI4MGE4NWI5MjllYjI4MTA2MmI5N2Q0OWI4NGY2MzI4NTE0MjY2N2UiCiAgICB9CiAgfQp9
Letters:
  EXAMPLE_LETTER:
    displayName: Example Letter
    model: 262 # must be even, greater than 260, and less than 400. The model if for the letter and quill. The next model up is for the written letter
Boxes:
  EXAMPLE_BOX:
    displayName: Example Box
    color: GRAY
    colorHighlight: LIME
    colorFlag: PINK
    profile: 5fb3fce3-729b-46cb-9f39-77335c0c1946
    texture: ewogICJ0aW1lc3RhbXAiIDogMTU5NjY0MzUzMzM4MSwKICAicHJvZmlsZUlkIiA6ICI5MThhMDI5NTU5ZGQ0Y2U2YjE2ZjdhNWQ1M2VmYjQxMiIsCiAgInByb2ZpbGVOYW1lIiA6ICJCZWV2ZWxvcGVyIiwKICAic2lnbmF0dXJlUmVxdWlyZWQiIDogdHJ1ZSwKICAidGV4dHVyZXMiIDogewogICAgIlNLSU4iIDogewogICAgICAidXJsIiA6ICJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2QyMTQzOTI0YWM5ODFiYmIwNGI5ZGUyODI4MGE4NWI5MjllYjI4MTA2MmI5N2Q0OWI4NGY2MzI4NTE0MjY2N2UiCiAgICB9CiAgfQp9